<?xml version="1.0" encoding="UTF-8"?>
<project name="GestionEleves-Ant" default="info" basedir=".">

    <property name="target.dir" value="target" />

    <target name="info">
        <echo message="Exécution des tâches Ant pour le projet Gestion Éleves" />
    </target>

    <target name="prepare">
        <echo message="Vérification du dossier target..." />
        <available file="${target.dir}" type="dir" property="target.exists" />
    </target>

</project>
