name: Java CI avec Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Java 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'oracle'
          cache: maven

      - name: Build avec Maven
        run: mvn -B package

      - name: Telecharger l'application WEB (WAR)
        uses: actions/upload-artifact@v4
        with:
          name: gestion-eleves-web
          path: "**/target/*.war"
