name: Mon Build Automatique

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Recuperer le code
      uses: actions/checkout@v4

    - name: Installer Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Compiler avec Maven
      run: mvn -B package # C'est ici que GitHub lit ton pom.xml

    - name: Sauvegarder le JAR
      uses: upload-artifact@v4
      with:
        name: mon-app-executable
        path: target/*.jar
